/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderPlacedRouteImport } from './routes/order-placed'
import { Route as DelyciasRouteImport } from './routes/delycias'
import { Route as ClearCookiesRouteImport } from './routes/clear-cookies'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPRouteImport } from './routes/user/p'
import { Route as UserLoginlocalRouteImport } from './routes/user/loginlocal'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as ResUsernameRouteImport } from './routes/res.$username'
import { Route as AuthMagicRouteImport } from './routes/auth/magic'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiReverificationCodeRouteImport } from './routes/api/reverification-code'
import { Route as ApiRestaurantRouteImport } from './routes/api/restaurant'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiUserUpdateRouteImport } from './routes/api/user.update'
import { Route as ApiRestaurantCheckoutRouteImport } from './routes/api/restaurant.checkout'
import { Route as ApiAuthVerifyMagicRouteImport } from './routes/api/auth/verify-magic'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthRequestMagicLinkRouteImport } from './routes/api/auth/request-magic-link'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAppTempSessionRouteImport } from './routes/api/app.temp-session'
import { Route as ApiUsersAuthHandleAuthRouteImport } from './routes/api/users.auth.handleAuth'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPlacedRoute = OrderPlacedRouteImport.update({
  id: '/order-placed',
  path: '/order-placed',
  getParentRoute: () => rootRouteImport,
} as any)
const DelyciasRoute = DelyciasRouteImport.update({
  id: '/delycias',
  path: '/delycias',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearCookiesRoute = ClearCookiesRouteImport.update({
  id: '/clear-cookies',
  path: '/clear-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPRoute = UserPRouteImport.update({
  id: '/user/p',
  path: '/user/p',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginlocalRoute = UserLoginlocalRouteImport.update({
  id: '/user/loginlocal',
  path: '/user/loginlocal',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResUsernameRoute = ResUsernameRouteImport.update({
  id: '/res/$username',
  path: '/res/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/auth/magic',
  path: '/auth/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReverificationCodeRoute = ApiReverificationCodeRouteImport.update({
  id: '/api/reverification-code',
  path: '/api/reverification-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantRoute = ApiRestaurantRouteImport.update({
  id: '/api/restaurant',
  path: '/api/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUpdateRoute = ApiUserUpdateRouteImport.update({
  id: '/api/user/update',
  path: '/api/user/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantCheckoutRoute = ApiRestaurantCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ApiRestaurantRoute,
} as any)
const ApiAuthVerifyMagicRoute = ApiAuthVerifyMagicRouteImport.update({
  id: '/api/auth/verify-magic',
  path: '/api/auth/verify-magic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestMagicLinkRoute = ApiAuthRequestMagicLinkRouteImport.update({
  id: '/api/auth/request-magic-link',
  path: '/api/auth/request-magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppTempSessionRoute = ApiAppTempSessionRouteImport.update({
  id: '/api/app/temp-session',
  path: '/api/app/temp-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersAuthHandleAuthRoute = ApiUsersAuthHandleAuthRouteImport.update({
  id: '/auth/handleAuth',
  path: '/auth/handleAuth',
  getParentRoute: () => ApiUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/clear-cookies': typeof ClearCookiesRoute
  '/delycias': typeof DelyciasRoute
  '/order-placed': typeof OrderPlacedRoute
  '/orders': typeof OrdersRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/restaurant': typeof ApiRestaurantRouteWithChildren
  '/api/reverification-code': typeof ApiReverificationCodeRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/auth/magic': typeof AuthMagicRoute
  '/res/$username': typeof ResUsernameRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/loginlocal': typeof UserLoginlocalRoute
  '/user/p': typeof UserPRoute
  '/api/app/temp-session': typeof ApiAppTempSessionRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/request-magic-link': typeof ApiAuthRequestMagicLinkRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-magic': typeof ApiAuthVerifyMagicRoute
  '/api/restaurant/checkout': typeof ApiRestaurantCheckoutRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/api/users/auth/handleAuth': typeof ApiUsersAuthHandleAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/clear-cookies': typeof ClearCookiesRoute
  '/delycias': typeof DelyciasRoute
  '/order-placed': typeof OrderPlacedRoute
  '/orders': typeof OrdersRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/restaurant': typeof ApiRestaurantRouteWithChildren
  '/api/reverification-code': typeof ApiReverificationCodeRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/auth/magic': typeof AuthMagicRoute
  '/res/$username': typeof ResUsernameRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/loginlocal': typeof UserLoginlocalRoute
  '/user/p': typeof UserPRoute
  '/api/app/temp-session': typeof ApiAppTempSessionRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/request-magic-link': typeof ApiAuthRequestMagicLinkRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-magic': typeof ApiAuthVerifyMagicRoute
  '/api/restaurant/checkout': typeof ApiRestaurantCheckoutRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/api/users/auth/handleAuth': typeof ApiUsersAuthHandleAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/clear-cookies': typeof ClearCookiesRoute
  '/delycias': typeof DelyciasRoute
  '/order-placed': typeof OrderPlacedRoute
  '/orders': typeof OrdersRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/restaurant': typeof ApiRestaurantRouteWithChildren
  '/api/reverification-code': typeof ApiReverificationCodeRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/auth/magic': typeof AuthMagicRoute
  '/res/$username': typeof ResUsernameRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/loginlocal': typeof UserLoginlocalRoute
  '/user/p': typeof UserPRoute
  '/api/app/temp-session': typeof ApiAppTempSessionRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/request-magic-link': typeof ApiAuthRequestMagicLinkRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-magic': typeof ApiAuthVerifyMagicRoute
  '/api/restaurant/checkout': typeof ApiRestaurantCheckoutRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/api/users/auth/handleAuth': typeof ApiUsersAuthHandleAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/clear-cookies'
    | '/delycias'
    | '/order-placed'
    | '/orders'
    | '/api/categories'
    | '/api/inventory'
    | '/api/orders'
    | '/api/restaurant'
    | '/api/reverification-code'
    | '/api/users'
    | '/auth/magic'
    | '/res/$username'
    | '/user/dashboard'
    | '/user/loginlocal'
    | '/user/p'
    | '/api/app/temp-session'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/request-magic-link'
    | '/api/auth/session'
    | '/api/auth/verify-magic'
    | '/api/restaurant/checkout'
    | '/api/user/update'
    | '/api/users/auth/handleAuth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/clear-cookies'
    | '/delycias'
    | '/order-placed'
    | '/orders'
    | '/api/categories'
    | '/api/inventory'
    | '/api/orders'
    | '/api/restaurant'
    | '/api/reverification-code'
    | '/api/users'
    | '/auth/magic'
    | '/res/$username'
    | '/user/dashboard'
    | '/user/loginlocal'
    | '/user/p'
    | '/api/app/temp-session'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/request-magic-link'
    | '/api/auth/session'
    | '/api/auth/verify-magic'
    | '/api/restaurant/checkout'
    | '/api/user/update'
    | '/api/users/auth/handleAuth'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/clear-cookies'
    | '/delycias'
    | '/order-placed'
    | '/orders'
    | '/api/categories'
    | '/api/inventory'
    | '/api/orders'
    | '/api/restaurant'
    | '/api/reverification-code'
    | '/api/users'
    | '/auth/magic'
    | '/res/$username'
    | '/user/dashboard'
    | '/user/loginlocal'
    | '/user/p'
    | '/api/app/temp-session'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/request-magic-link'
    | '/api/auth/session'
    | '/api/auth/verify-magic'
    | '/api/restaurant/checkout'
    | '/api/user/update'
    | '/api/users/auth/handleAuth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CategoryRoute: typeof CategoryRoute
  CheckoutRoute: typeof CheckoutRoute
  ClearCookiesRoute: typeof ClearCookiesRoute
  DelyciasRoute: typeof DelyciasRoute
  OrderPlacedRoute: typeof OrderPlacedRoute
  OrdersRoute: typeof OrdersRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiInventoryRoute: typeof ApiInventoryRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiRestaurantRoute: typeof ApiRestaurantRouteWithChildren
  ApiReverificationCodeRoute: typeof ApiReverificationCodeRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  AuthMagicRoute: typeof AuthMagicRoute
  ResUsernameRoute: typeof ResUsernameRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserLoginlocalRoute: typeof UserLoginlocalRoute
  UserPRoute: typeof UserPRoute
  ApiAppTempSessionRoute: typeof ApiAppTempSessionRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthRequestMagicLinkRoute: typeof ApiAuthRequestMagicLinkRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthVerifyMagicRoute: typeof ApiAuthVerifyMagicRoute
  ApiUserUpdateRoute: typeof ApiUserUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-placed': {
      id: '/order-placed'
      path: '/order-placed'
      fullPath: '/order-placed'
      preLoaderRoute: typeof OrderPlacedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delycias': {
      id: '/delycias'
      path: '/delycias'
      fullPath: '/delycias'
      preLoaderRoute: typeof DelyciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clear-cookies': {
      id: '/clear-cookies'
      path: '/clear-cookies'
      fullPath: '/clear-cookies'
      preLoaderRoute: typeof ClearCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/p': {
      id: '/user/p'
      path: '/user/p'
      fullPath: '/user/p'
      preLoaderRoute: typeof UserPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/loginlocal': {
      id: '/user/loginlocal'
      path: '/user/loginlocal'
      fullPath: '/user/loginlocal'
      preLoaderRoute: typeof UserLoginlocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/res/$username': {
      id: '/res/$username'
      path: '/res/$username'
      fullPath: '/res/$username'
      preLoaderRoute: typeof ResUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic': {
      id: '/auth/magic'
      path: '/auth/magic'
      fullPath: '/auth/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reverification-code': {
      id: '/api/reverification-code'
      path: '/api/reverification-code'
      fullPath: '/api/reverification-code'
      preLoaderRoute: typeof ApiReverificationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurant': {
      id: '/api/restaurant'
      path: '/api/restaurant'
      fullPath: '/api/restaurant'
      preLoaderRoute: typeof ApiRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/update': {
      id: '/api/user/update'
      path: '/api/user/update'
      fullPath: '/api/user/update'
      preLoaderRoute: typeof ApiUserUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurant/checkout': {
      id: '/api/restaurant/checkout'
      path: '/checkout'
      fullPath: '/api/restaurant/checkout'
      preLoaderRoute: typeof ApiRestaurantCheckoutRouteImport
      parentRoute: typeof ApiRestaurantRoute
    }
    '/api/auth/verify-magic': {
      id: '/api/auth/verify-magic'
      path: '/api/auth/verify-magic'
      fullPath: '/api/auth/verify-magic'
      preLoaderRoute: typeof ApiAuthVerifyMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-magic-link': {
      id: '/api/auth/request-magic-link'
      path: '/api/auth/request-magic-link'
      fullPath: '/api/auth/request-magic-link'
      preLoaderRoute: typeof ApiAuthRequestMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app/temp-session': {
      id: '/api/app/temp-session'
      path: '/api/app/temp-session'
      fullPath: '/api/app/temp-session'
      preLoaderRoute: typeof ApiAppTempSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/auth/handleAuth': {
      id: '/api/users/auth/handleAuth'
      path: '/auth/handleAuth'
      fullPath: '/api/users/auth/handleAuth'
      preLoaderRoute: typeof ApiUsersAuthHandleAuthRouteImport
      parentRoute: typeof ApiUsersRoute
    }
  }
}

interface ApiRestaurantRouteChildren {
  ApiRestaurantCheckoutRoute: typeof ApiRestaurantCheckoutRoute
}

const ApiRestaurantRouteChildren: ApiRestaurantRouteChildren = {
  ApiRestaurantCheckoutRoute: ApiRestaurantCheckoutRoute,
}

const ApiRestaurantRouteWithChildren = ApiRestaurantRoute._addFileChildren(
  ApiRestaurantRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersAuthHandleAuthRoute: typeof ApiUsersAuthHandleAuthRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersAuthHandleAuthRoute: ApiUsersAuthHandleAuthRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CategoryRoute: CategoryRoute,
  CheckoutRoute: CheckoutRoute,
  ClearCookiesRoute: ClearCookiesRoute,
  DelyciasRoute: DelyciasRoute,
  OrderPlacedRoute: OrderPlacedRoute,
  OrdersRoute: OrdersRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiInventoryRoute: ApiInventoryRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiRestaurantRoute: ApiRestaurantRouteWithChildren,
  ApiReverificationCodeRoute: ApiReverificationCodeRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  AuthMagicRoute: AuthMagicRoute,
  ResUsernameRoute: ResUsernameRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserLoginlocalRoute: UserLoginlocalRoute,
  UserPRoute: UserPRoute,
  ApiAppTempSessionRoute: ApiAppTempSessionRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthRequestMagicLinkRoute: ApiAuthRequestMagicLinkRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthVerifyMagicRoute: ApiAuthVerifyMagicRoute,
  ApiUserUpdateRoute: ApiUserUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
