/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderPlacedRouteImport } from './routes/order-placed'
import { Route as DelyciasRouteImport } from './routes/delycias'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPRouteImport } from './routes/user/p'
import { Route as UserLoginlocalRouteImport } from './routes/user/loginlocal'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as ResUsernameRouteImport } from './routes/res.$username'
import { Route as ApiVerifyRouteImport } from './routes/api/verify'
import { Route as ApiReverificationCodeRouteImport } from './routes/api/reverification-code'
import { Route as ApiRestaurantRouteImport } from './routes/api/restaurant'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiUserUpdateRouteImport } from './routes/api/user.update'
import { Route as ApiRestaurantCheckoutRouteImport } from './routes/api/restaurant.checkout'
import { Route as ApiAppTempSessionRouteImport } from './routes/api/app.temp-session'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiUsersAuthRefreshRouteImport } from './routes/api/users.auth.refresh'
import { Route as ApiUsersAuthHandleAuthRouteImport } from './routes/api/users.auth.handleAuth'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPlacedRoute = OrderPlacedRouteImport.update({
  id: '/order-placed',
  path: '/order-placed',
  getParentRoute: () => rootRouteImport,
} as any)
const DelyciasRoute = DelyciasRouteImport.update({
  id: '/delycias',
  path: '/delycias',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPRoute = UserPRouteImport.update({
  id: '/user/p',
  path: '/user/p',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginlocalRoute = UserLoginlocalRouteImport.update({
  id: '/user/loginlocal',
  path: '/user/loginlocal',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResUsernameRoute = ResUsernameRouteImport.update({
  id: '/res/$username',
  path: '/res/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRoute = ApiVerifyRouteImport.update({
  id: '/api/verify',
  path: '/api/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReverificationCodeRoute = ApiReverificationCodeRouteImport.update({
  id: '/api/reverification-code',
  path: '/api/reverification-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantRoute = ApiRestaurantRouteImport.update({
  id: '/api/restaurant',
  path: '/api/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUpdateRoute = ApiUserUpdateRouteImport.update({
  id: '/api/user/update',
  path: '/api/user/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantCheckoutRoute = ApiRestaurantCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ApiRestaurantRoute,
} as any)
const ApiAppTempSessionRoute = ApiAppTempSessionRouteImport.update({
  id: '/api/app/temp-session',
  path: '/api/app/temp-session',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersAuthRefreshRoute = ApiUsersAuthRefreshRouteImport.update({
  id: '/api/users/auth/refresh',
  path: '/api/users/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersAuthHandleAuthRoute = ApiUsersAuthHandleAuthRouteImport.update({
  id: '/api/users/auth/handleAuth',
  path: '/api/users/auth/handleAuth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/delycias': typeof DelyciasRoute
  '/order-placed': typeof OrderPlacedRoute
  '/orders': typeof OrdersRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/restaurant': typeof ApiRestaurantRouteWithChildren
  '/api/reverification-code': typeof ApiReverificationCodeRoute
  '/api/verify': typeof ApiVerifyRoute
  '/res/$username': typeof ResUsernameRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/loginlocal': typeof UserLoginlocalRoute
  '/user/p': typeof UserPRoute
  '/api/app/temp-session': typeof ApiAppTempSessionRoute
  '/api/restaurant/checkout': typeof ApiRestaurantCheckoutRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/users/auth/handleAuth': typeof ApiUsersAuthHandleAuthRoute
  '/api/users/auth/refresh': typeof ApiUsersAuthRefreshRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/delycias': typeof DelyciasRoute
  '/order-placed': typeof OrderPlacedRoute
  '/orders': typeof OrdersRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/restaurant': typeof ApiRestaurantRouteWithChildren
  '/api/reverification-code': typeof ApiReverificationCodeRoute
  '/api/verify': typeof ApiVerifyRoute
  '/res/$username': typeof ResUsernameRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/loginlocal': typeof UserLoginlocalRoute
  '/user/p': typeof UserPRoute
  '/api/app/temp-session': typeof ApiAppTempSessionRoute
  '/api/restaurant/checkout': typeof ApiRestaurantCheckoutRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/users/auth/handleAuth': typeof ApiUsersAuthHandleAuthRoute
  '/api/users/auth/refresh': typeof ApiUsersAuthRefreshRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/delycias': typeof DelyciasRoute
  '/order-placed': typeof OrderPlacedRoute
  '/orders': typeof OrdersRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/inventory': typeof ApiInventoryRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/restaurant': typeof ApiRestaurantRouteWithChildren
  '/api/reverification-code': typeof ApiReverificationCodeRoute
  '/api/verify': typeof ApiVerifyRoute
  '/res/$username': typeof ResUsernameRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/loginlocal': typeof UserLoginlocalRoute
  '/user/p': typeof UserPRoute
  '/api/app/temp-session': typeof ApiAppTempSessionRoute
  '/api/restaurant/checkout': typeof ApiRestaurantCheckoutRoute
  '/api/user/update': typeof ApiUserUpdateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/users/auth/handleAuth': typeof ApiUsersAuthHandleAuthRoute
  '/api/users/auth/refresh': typeof ApiUsersAuthRefreshRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/delycias'
    | '/order-placed'
    | '/orders'
    | '/api/categories'
    | '/api/inventory'
    | '/api/orders'
    | '/api/restaurant'
    | '/api/reverification-code'
    | '/api/verify'
    | '/res/$username'
    | '/user/dashboard'
    | '/user/loginlocal'
    | '/user/p'
    | '/api/app/temp-session'
    | '/api/restaurant/checkout'
    | '/api/user/update'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/users/auth/handleAuth'
    | '/api/users/auth/refresh'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/delycias'
    | '/order-placed'
    | '/orders'
    | '/api/categories'
    | '/api/inventory'
    | '/api/orders'
    | '/api/restaurant'
    | '/api/reverification-code'
    | '/api/verify'
    | '/res/$username'
    | '/user/dashboard'
    | '/user/loginlocal'
    | '/user/p'
    | '/api/app/temp-session'
    | '/api/restaurant/checkout'
    | '/api/user/update'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/users/auth/handleAuth'
    | '/api/users/auth/refresh'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/delycias'
    | '/order-placed'
    | '/orders'
    | '/api/categories'
    | '/api/inventory'
    | '/api/orders'
    | '/api/restaurant'
    | '/api/reverification-code'
    | '/api/verify'
    | '/res/$username'
    | '/user/dashboard'
    | '/user/loginlocal'
    | '/user/p'
    | '/api/app/temp-session'
    | '/api/restaurant/checkout'
    | '/api/user/update'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/users/auth/handleAuth'
    | '/api/users/auth/refresh'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CategoryRoute: typeof CategoryRoute
  CheckoutRoute: typeof CheckoutRoute
  DelyciasRoute: typeof DelyciasRoute
  OrderPlacedRoute: typeof OrderPlacedRoute
  OrdersRoute: typeof OrdersRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiInventoryRoute: typeof ApiInventoryRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiRestaurantRoute: typeof ApiRestaurantRouteWithChildren
  ApiReverificationCodeRoute: typeof ApiReverificationCodeRoute
  ApiVerifyRoute: typeof ApiVerifyRoute
  ResUsernameRoute: typeof ResUsernameRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserLoginlocalRoute: typeof UserLoginlocalRoute
  UserPRoute: typeof UserPRoute
  ApiAppTempSessionRoute: typeof ApiAppTempSessionRoute
  ApiUserUpdateRoute: typeof ApiUserUpdateRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiUsersAuthHandleAuthRoute: typeof ApiUsersAuthHandleAuthRoute
  ApiUsersAuthRefreshRoute: typeof ApiUsersAuthRefreshRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-placed': {
      id: '/order-placed'
      path: '/order-placed'
      fullPath: '/order-placed'
      preLoaderRoute: typeof OrderPlacedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delycias': {
      id: '/delycias'
      path: '/delycias'
      fullPath: '/delycias'
      preLoaderRoute: typeof DelyciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/p': {
      id: '/user/p'
      path: '/user/p'
      fullPath: '/user/p'
      preLoaderRoute: typeof UserPRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/loginlocal': {
      id: '/user/loginlocal'
      path: '/user/loginlocal'
      fullPath: '/user/loginlocal'
      preLoaderRoute: typeof UserLoginlocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/res/$username': {
      id: '/res/$username'
      path: '/res/$username'
      fullPath: '/res/$username'
      preLoaderRoute: typeof ResUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify': {
      id: '/api/verify'
      path: '/api/verify'
      fullPath: '/api/verify'
      preLoaderRoute: typeof ApiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reverification-code': {
      id: '/api/reverification-code'
      path: '/api/reverification-code'
      fullPath: '/api/reverification-code'
      preLoaderRoute: typeof ApiReverificationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurant': {
      id: '/api/restaurant'
      path: '/api/restaurant'
      fullPath: '/api/restaurant'
      preLoaderRoute: typeof ApiRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/update': {
      id: '/api/user/update'
      path: '/api/user/update'
      fullPath: '/api/user/update'
      preLoaderRoute: typeof ApiUserUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurant/checkout': {
      id: '/api/restaurant/checkout'
      path: '/checkout'
      fullPath: '/api/restaurant/checkout'
      preLoaderRoute: typeof ApiRestaurantCheckoutRouteImport
      parentRoute: typeof ApiRestaurantRoute
    }
    '/api/app/temp-session': {
      id: '/api/app/temp-session'
      path: '/api/app/temp-session'
      fullPath: '/api/app/temp-session'
      preLoaderRoute: typeof ApiAppTempSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/auth/refresh': {
      id: '/api/users/auth/refresh'
      path: '/api/users/auth/refresh'
      fullPath: '/api/users/auth/refresh'
      preLoaderRoute: typeof ApiUsersAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/auth/handleAuth': {
      id: '/api/users/auth/handleAuth'
      path: '/api/users/auth/handleAuth'
      fullPath: '/api/users/auth/handleAuth'
      preLoaderRoute: typeof ApiUsersAuthHandleAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiRestaurantRouteChildren {
  ApiRestaurantCheckoutRoute: typeof ApiRestaurantCheckoutRoute
}

const ApiRestaurantRouteChildren: ApiRestaurantRouteChildren = {
  ApiRestaurantCheckoutRoute: ApiRestaurantCheckoutRoute,
}

const ApiRestaurantRouteWithChildren = ApiRestaurantRoute._addFileChildren(
  ApiRestaurantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CategoryRoute: CategoryRoute,
  CheckoutRoute: CheckoutRoute,
  DelyciasRoute: DelyciasRoute,
  OrderPlacedRoute: OrderPlacedRoute,
  OrdersRoute: OrdersRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiInventoryRoute: ApiInventoryRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiRestaurantRoute: ApiRestaurantRouteWithChildren,
  ApiReverificationCodeRoute: ApiReverificationCodeRoute,
  ApiVerifyRoute: ApiVerifyRoute,
  ResUsernameRoute: ResUsernameRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserLoginlocalRoute: UserLoginlocalRoute,
  UserPRoute: UserPRoute,
  ApiAppTempSessionRoute: ApiAppTempSessionRoute,
  ApiUserUpdateRoute: ApiUserUpdateRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiUsersAuthHandleAuthRoute: ApiUsersAuthHandleAuthRoute,
  ApiUsersAuthRefreshRoute: ApiUsersAuthRefreshRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
