/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickBillRouteImport } from './routes/quick-bill'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderHistoryRouteImport } from './routes/order-history'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookTableRouteImport } from './routes/book-table'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ApiWsTokenRouteImport } from './routes/api/ws-token'
import { Route as ApiWaiterOrdersRouteImport } from './routes/api/waiter-orders'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiTableRouteImport } from './routes/api/table'
import { Route as ApiRestaurantRouteImport } from './routes/api/restaurant'
import { Route as ApiQuickBillRouteImport } from './routes/api/quick-bill'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiImagekitRouteImport } from './routes/api/imagekit'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiCategoryRouteImport } from './routes/api/category'
import { Route as ApiAddonsRouteImport } from './routes/api/addons'
import { Route as UsersPIndexRouteImport } from './routes/users/p/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiInventoryBulkRouteImport } from './routes/api/inventory.bulk'
import { Route as ApiCategoryFromTemplatesRouteImport } from './routes/api/category/from-templates'
import { Route as ApiCategoryCuisineTypesRouteImport } from './routes/api/category/cuisine-types'
import { Route as ApiCategoryAsTemplateRouteImport } from './routes/api/category/as-template'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUpdateRouteImport } from './routes/api/admin.update'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiCategoryTemplatesCuisineRouteImport } from './routes/api/category/templates/$cuisine'

const QuickBillRoute = QuickBillRouteImport.update({
  id: '/quick-bill',
  path: '/quick-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryRoute = OrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTableRoute = BookTableRouteImport.update({
  id: '/book-table',
  path: '/book-table',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsTokenRoute = ApiWsTokenRouteImport.update({
  id: '/api/ws-token',
  path: '/api/ws-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaiterOrdersRoute = ApiWaiterOrdersRouteImport.update({
  id: '/api/waiter-orders',
  path: '/api/waiter-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTableRoute = ApiTableRouteImport.update({
  id: '/api/table',
  path: '/api/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantRoute = ApiRestaurantRouteImport.update({
  id: '/api/restaurant',
  path: '/api/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickBillRoute = ApiQuickBillRouteImport.update({
  id: '/api/quick-bill',
  path: '/api/quick-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagekitRoute = ApiImagekitRouteImport.update({
  id: '/api/imagekit',
  path: '/api/imagekit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoryRoute = ApiCategoryRouteImport.update({
  id: '/api/category',
  path: '/api/category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddonsRoute = ApiAddonsRouteImport.update({
  id: '/api/addons',
  path: '/api/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersPIndexRoute = UsersPIndexRouteImport.update({
  id: '/users/p/',
  path: '/users/p/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryBulkRoute = ApiInventoryBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ApiInventoryRoute,
} as any)
const ApiCategoryFromTemplatesRoute =
  ApiCategoryFromTemplatesRouteImport.update({
    id: '/from-templates',
    path: '/from-templates',
    getParentRoute: () => ApiCategoryRoute,
  } as any)
const ApiCategoryCuisineTypesRoute = ApiCategoryCuisineTypesRouteImport.update({
  id: '/cuisine-types',
  path: '/cuisine-types',
  getParentRoute: () => ApiCategoryRoute,
} as any)
const ApiCategoryAsTemplateRoute = ApiCategoryAsTemplateRouteImport.update({
  id: '/as-template',
  path: '/as-template',
  getParentRoute: () => ApiCategoryRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateRoute = ApiAdminUpdateRouteImport.update({
  id: '/api/admin/update',
  path: '/api/admin/update',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoryTemplatesCuisineRoute =
  ApiCategoryTemplatesCuisineRouteImport.update({
    id: '/templates/$cuisine',
    path: '/templates/$cuisine',
    getParentRoute: () => ApiCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/book-table': typeof BookTableRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-history': typeof OrderHistoryRoute
  '/orders': typeof OrdersRoute
  '/quick-bill': typeof QuickBillRoute
  '/api/addons': typeof ApiAddonsRoute
  '/api/category': typeof ApiCategoryRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/imagekit': typeof ApiImagekitRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/orders': typeof ApiOrdersRoute
  '/api/quick-bill': typeof ApiQuickBillRoute
  '/api/restaurant': typeof ApiRestaurantRoute
  '/api/table': typeof ApiTableRoute
  '/api/users': typeof ApiUsersRoute
  '/api/waiter-orders': typeof ApiWaiterOrdersRoute
  '/api/ws-token': typeof ApiWsTokenRoute
  '/users': typeof UsersIndexRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/category/as-template': typeof ApiCategoryAsTemplateRoute
  '/api/category/cuisine-types': typeof ApiCategoryCuisineTypesRoute
  '/api/category/from-templates': typeof ApiCategoryFromTemplatesRoute
  '/api/inventory/bulk': typeof ApiInventoryBulkRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/users/p': typeof UsersPIndexRoute
  '/api/category/templates/$cuisine': typeof ApiCategoryTemplatesCuisineRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/book-table': typeof BookTableRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-history': typeof OrderHistoryRoute
  '/orders': typeof OrdersRoute
  '/quick-bill': typeof QuickBillRoute
  '/api/addons': typeof ApiAddonsRoute
  '/api/category': typeof ApiCategoryRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/imagekit': typeof ApiImagekitRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/orders': typeof ApiOrdersRoute
  '/api/quick-bill': typeof ApiQuickBillRoute
  '/api/restaurant': typeof ApiRestaurantRoute
  '/api/table': typeof ApiTableRoute
  '/api/users': typeof ApiUsersRoute
  '/api/waiter-orders': typeof ApiWaiterOrdersRoute
  '/api/ws-token': typeof ApiWsTokenRoute
  '/users': typeof UsersIndexRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/category/as-template': typeof ApiCategoryAsTemplateRoute
  '/api/category/cuisine-types': typeof ApiCategoryCuisineTypesRoute
  '/api/category/from-templates': typeof ApiCategoryFromTemplatesRoute
  '/api/inventory/bulk': typeof ApiInventoryBulkRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/users/p': typeof UsersPIndexRoute
  '/api/category/templates/$cuisine': typeof ApiCategoryTemplatesCuisineRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/book-table': typeof BookTableRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-history': typeof OrderHistoryRoute
  '/orders': typeof OrdersRoute
  '/quick-bill': typeof QuickBillRoute
  '/api/addons': typeof ApiAddonsRoute
  '/api/category': typeof ApiCategoryRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/imagekit': typeof ApiImagekitRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/orders': typeof ApiOrdersRoute
  '/api/quick-bill': typeof ApiQuickBillRoute
  '/api/restaurant': typeof ApiRestaurantRoute
  '/api/table': typeof ApiTableRoute
  '/api/users': typeof ApiUsersRoute
  '/api/waiter-orders': typeof ApiWaiterOrdersRoute
  '/api/ws-token': typeof ApiWsTokenRoute
  '/users/': typeof UsersIndexRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/category/as-template': typeof ApiCategoryAsTemplateRoute
  '/api/category/cuisine-types': typeof ApiCategoryCuisineTypesRoute
  '/api/category/from-templates': typeof ApiCategoryFromTemplatesRoute
  '/api/inventory/bulk': typeof ApiInventoryBulkRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/users/p/': typeof UsersPIndexRoute
  '/api/category/templates/$cuisine': typeof ApiCategoryTemplatesCuisineRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/book-table'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/order-history'
    | '/orders'
    | '/quick-bill'
    | '/api/addons'
    | '/api/category'
    | '/api/dashboard'
    | '/api/imagekit'
    | '/api/inventory'
    | '/api/orders'
    | '/api/quick-bill'
    | '/api/restaurant'
    | '/api/table'
    | '/api/users'
    | '/api/waiter-orders'
    | '/api/ws-token'
    | '/users'
    | '/api/admin/update'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/session'
    | '/api/category/as-template'
    | '/api/category/cuisine-types'
    | '/api/category/from-templates'
    | '/api/inventory/bulk'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/users/p'
    | '/api/category/templates/$cuisine'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/book-table'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/order-history'
    | '/orders'
    | '/quick-bill'
    | '/api/addons'
    | '/api/category'
    | '/api/dashboard'
    | '/api/imagekit'
    | '/api/inventory'
    | '/api/orders'
    | '/api/quick-bill'
    | '/api/restaurant'
    | '/api/table'
    | '/api/users'
    | '/api/waiter-orders'
    | '/api/ws-token'
    | '/users'
    | '/api/admin/update'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/session'
    | '/api/category/as-template'
    | '/api/category/cuisine-types'
    | '/api/category/from-templates'
    | '/api/inventory/bulk'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/users/p'
    | '/api/category/templates/$cuisine'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/book-table'
    | '/dashboard'
    | '/login'
    | '/menu'
    | '/order-history'
    | '/orders'
    | '/quick-bill'
    | '/api/addons'
    | '/api/category'
    | '/api/dashboard'
    | '/api/imagekit'
    | '/api/inventory'
    | '/api/orders'
    | '/api/quick-bill'
    | '/api/restaurant'
    | '/api/table'
    | '/api/users'
    | '/api/waiter-orders'
    | '/api/ws-token'
    | '/users/'
    | '/api/admin/update'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/session'
    | '/api/category/as-template'
    | '/api/category/cuisine-types'
    | '/api/category/from-templates'
    | '/api/inventory/bulk'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/users/p/'
    | '/api/category/templates/$cuisine'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  BookTableRoute: typeof BookTableRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrderHistoryRoute: typeof OrderHistoryRoute
  OrdersRoute: typeof OrdersRoute
  QuickBillRoute: typeof QuickBillRoute
  ApiAddonsRoute: typeof ApiAddonsRoute
  ApiCategoryRoute: typeof ApiCategoryRouteWithChildren
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiImagekitRoute: typeof ApiImagekitRoute
  ApiInventoryRoute: typeof ApiInventoryRouteWithChildren
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiQuickBillRoute: typeof ApiQuickBillRoute
  ApiRestaurantRoute: typeof ApiRestaurantRoute
  ApiTableRoute: typeof ApiTableRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiWaiterOrdersRoute: typeof ApiWaiterOrdersRoute
  ApiWsTokenRoute: typeof ApiWsTokenRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApiAdminUpdateRoute: typeof ApiAdminUpdateRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  UsersPIndexRoute: typeof UsersPIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick-bill': {
      id: '/quick-bill'
      path: '/quick-bill'
      fullPath: '/quick-bill'
      preLoaderRoute: typeof QuickBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-history': {
      id: '/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof OrderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-table': {
      id: '/book-table'
      path: '/book-table'
      fullPath: '/book-table'
      preLoaderRoute: typeof BookTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws-token': {
      id: '/api/ws-token'
      path: '/api/ws-token'
      fullPath: '/api/ws-token'
      preLoaderRoute: typeof ApiWsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waiter-orders': {
      id: '/api/waiter-orders'
      path: '/api/waiter-orders'
      fullPath: '/api/waiter-orders'
      preLoaderRoute: typeof ApiWaiterOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/table': {
      id: '/api/table'
      path: '/api/table'
      fullPath: '/api/table'
      preLoaderRoute: typeof ApiTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurant': {
      id: '/api/restaurant'
      path: '/api/restaurant'
      fullPath: '/api/restaurant'
      preLoaderRoute: typeof ApiRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-bill': {
      id: '/api/quick-bill'
      path: '/api/quick-bill'
      fullPath: '/api/quick-bill'
      preLoaderRoute: typeof ApiQuickBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imagekit': {
      id: '/api/imagekit'
      path: '/api/imagekit'
      fullPath: '/api/imagekit'
      preLoaderRoute: typeof ApiImagekitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category': {
      id: '/api/category'
      path: '/api/category'
      fullPath: '/api/category'
      preLoaderRoute: typeof ApiCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/addons': {
      id: '/api/addons'
      path: '/api/addons'
      fullPath: '/api/addons'
      preLoaderRoute: typeof ApiAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/p/': {
      id: '/users/p/'
      path: '/users/p'
      fullPath: '/users/p'
      preLoaderRoute: typeof UsersPIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/bulk': {
      id: '/api/inventory/bulk'
      path: '/bulk'
      fullPath: '/api/inventory/bulk'
      preLoaderRoute: typeof ApiInventoryBulkRouteImport
      parentRoute: typeof ApiInventoryRoute
    }
    '/api/category/from-templates': {
      id: '/api/category/from-templates'
      path: '/from-templates'
      fullPath: '/api/category/from-templates'
      preLoaderRoute: typeof ApiCategoryFromTemplatesRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
    '/api/category/cuisine-types': {
      id: '/api/category/cuisine-types'
      path: '/cuisine-types'
      fullPath: '/api/category/cuisine-types'
      preLoaderRoute: typeof ApiCategoryCuisineTypesRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
    '/api/category/as-template': {
      id: '/api/category/as-template'
      path: '/as-template'
      fullPath: '/api/category/as-template'
      preLoaderRoute: typeof ApiCategoryAsTemplateRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update': {
      id: '/api/admin/update'
      path: '/api/admin/update'
      fullPath: '/api/admin/update'
      preLoaderRoute: typeof ApiAdminUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category/templates/$cuisine': {
      id: '/api/category/templates/$cuisine'
      path: '/templates/$cuisine'
      fullPath: '/api/category/templates/$cuisine'
      preLoaderRoute: typeof ApiCategoryTemplatesCuisineRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
  }
}

interface ApiCategoryRouteChildren {
  ApiCategoryAsTemplateRoute: typeof ApiCategoryAsTemplateRoute
  ApiCategoryCuisineTypesRoute: typeof ApiCategoryCuisineTypesRoute
  ApiCategoryFromTemplatesRoute: typeof ApiCategoryFromTemplatesRoute
  ApiCategoryTemplatesCuisineRoute: typeof ApiCategoryTemplatesCuisineRoute
}

const ApiCategoryRouteChildren: ApiCategoryRouteChildren = {
  ApiCategoryAsTemplateRoute: ApiCategoryAsTemplateRoute,
  ApiCategoryCuisineTypesRoute: ApiCategoryCuisineTypesRoute,
  ApiCategoryFromTemplatesRoute: ApiCategoryFromTemplatesRoute,
  ApiCategoryTemplatesCuisineRoute: ApiCategoryTemplatesCuisineRoute,
}

const ApiCategoryRouteWithChildren = ApiCategoryRoute._addFileChildren(
  ApiCategoryRouteChildren,
)

interface ApiInventoryRouteChildren {
  ApiInventoryBulkRoute: typeof ApiInventoryBulkRoute
}

const ApiInventoryRouteChildren: ApiInventoryRouteChildren = {
  ApiInventoryBulkRoute: ApiInventoryBulkRoute,
}

const ApiInventoryRouteWithChildren = ApiInventoryRoute._addFileChildren(
  ApiInventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  BookTableRoute: BookTableRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrderHistoryRoute: OrderHistoryRoute,
  OrdersRoute: OrdersRoute,
  QuickBillRoute: QuickBillRoute,
  ApiAddonsRoute: ApiAddonsRoute,
  ApiCategoryRoute: ApiCategoryRouteWithChildren,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiImagekitRoute: ApiImagekitRoute,
  ApiInventoryRoute: ApiInventoryRouteWithChildren,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiQuickBillRoute: ApiQuickBillRoute,
  ApiRestaurantRoute: ApiRestaurantRoute,
  ApiTableRoute: ApiTableRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiWaiterOrdersRoute: ApiWaiterOrdersRoute,
  ApiWsTokenRoute: ApiWsTokenRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApiAdminUpdateRoute: ApiAdminUpdateRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  UsersPIndexRoute: UsersPIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
