/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as BillingIndexRouteImport } from './routes/billing/index'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings/subscription'
import { Route as ReportsSalesRouteImport } from './routes/reports/sales'
import { Route as ReportsCrmRouteImport } from './routes/reports/crm'
import { Route as OrdersOverviewRouteImport } from './routes/orders/overview'
import { Route as OrdersHistoryRouteImport } from './routes/orders/history'
import { Route as InventoryStockRouteImport } from './routes/inventory/stock'
import { Route as InventoryMenuRouteImport } from './routes/inventory/menu'
import { Route as BillingQuickBillRouteImport } from './routes/billing/quick-bill'
import { Route as BillingBookTableRouteImport } from './routes/billing/book-table'
import { Route as ApiWsTokenRouteImport } from './routes/api/ws-token'
import { Route as ApiWaiterOrdersRouteImport } from './routes/api/waiter-orders'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiTableRouteImport } from './routes/api/table'
import { Route as ApiSubscriptionRouteImport } from './routes/api/subscription'
import { Route as ApiStaffReportsRouteImport } from './routes/api/staff-reports'
import { Route as ApiRestaurantRouteImport } from './routes/api/restaurant'
import { Route as ApiQuickBillRouteImport } from './routes/api/quick-bill'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiInventoryStatsRouteImport } from './routes/api/inventory-stats'
import { Route as ApiInventoryRouteImport } from './routes/api/inventory'
import { Route as ApiImagekitRouteImport } from './routes/api/imagekit'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiCrmRouteImport } from './routes/api/crm'
import { Route as ApiCategoryRouteImport } from './routes/api/category'
import { Route as ApiAddonsRouteImport } from './routes/api/addons'
import { Route as UsersPIndexRouteImport } from './routes/users/p/index'
import { Route as ReportsStaffIndexRouteImport } from './routes/reports/staff/index'
import { Route as ReportsInventoryIndexRouteImport } from './routes/reports/inventory/index'
import { Route as ReportsStaffStaffIdRouteImport } from './routes/reports/staff/$staffId'
import { Route as ReportsInventoryInventoryIdRouteImport } from './routes/reports/inventory/$inventoryId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiUsersSearchRouteImport } from './routes/api/users.search'
import { Route as ApiSubscriptionPlansRouteImport } from './routes/api/subscription.plans'
import { Route as ApiStaffReportsStaffIdRouteImport } from './routes/api/staff-reports/$staffId'
import { Route as ApiOrdersOrderHistoryRouteImport } from './routes/api/orders/order-history'
import { Route as ApiOrdersByTableRouteImport } from './routes/api/orders/by-table'
import { Route as ApiOrdersActionsRouteImport } from './routes/api/orders/actions'
import { Route as ApiInventoryBulkRouteImport } from './routes/api/inventory.bulk'
import { Route as ApiCrmStatsRouteImport } from './routes/api/crm/stats'
import { Route as ApiCrmDetailsRouteImport } from './routes/api/crm/details'
import { Route as ApiCategoryFromTemplatesRouteImport } from './routes/api/category/from-templates'
import { Route as ApiCategoryCuisineTypesRouteImport } from './routes/api/category/cuisine-types'
import { Route as ApiCategoryAsTemplateRouteImport } from './routes/api/category/as-template'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCreateAdminRouteImport } from './routes/api/auth/create-admin'
import { Route as ApiAdminUpdateRouteImport } from './routes/api/admin.update'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiCategoryTemplatesCuisineRouteImport } from './routes/api/category/templates/$cuisine'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/settings/subscription',
  path: '/settings/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCrmRoute = ReportsCrmRouteImport.update({
  id: '/reports/crm',
  path: '/reports/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOverviewRoute = OrdersOverviewRouteImport.update({
  id: '/orders/overview',
  path: '/orders/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersHistoryRoute = OrdersHistoryRouteImport.update({
  id: '/orders/history',
  path: '/orders/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStockRoute = InventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryMenuRoute = InventoryMenuRouteImport.update({
  id: '/inventory/menu',
  path: '/inventory/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingQuickBillRoute = BillingQuickBillRouteImport.update({
  id: '/billing/quick-bill',
  path: '/billing/quick-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingBookTableRoute = BillingBookTableRouteImport.update({
  id: '/billing/book-table',
  path: '/billing/book-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsTokenRoute = ApiWsTokenRouteImport.update({
  id: '/api/ws-token',
  path: '/api/ws-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaiterOrdersRoute = ApiWaiterOrdersRouteImport.update({
  id: '/api/waiter-orders',
  path: '/api/waiter-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTableRoute = ApiTableRouteImport.update({
  id: '/api/table',
  path: '/api/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffReportsRoute = ApiStaffReportsRouteImport.update({
  id: '/api/staff-reports',
  path: '/api/staff-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRestaurantRoute = ApiRestaurantRouteImport.update({
  id: '/api/restaurant',
  path: '/api/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickBillRoute = ApiQuickBillRouteImport.update({
  id: '/api/quick-bill',
  path: '/api/quick-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryStatsRoute = ApiInventoryStatsRouteImport.update({
  id: '/api/inventory-stats',
  path: '/api/inventory-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryRoute = ApiInventoryRouteImport.update({
  id: '/api/inventory',
  path: '/api/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagekitRoute = ApiImagekitRouteImport.update({
  id: '/api/imagekit',
  path: '/api/imagekit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmRoute = ApiCrmRouteImport.update({
  id: '/api/crm',
  path: '/api/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoryRoute = ApiCategoryRouteImport.update({
  id: '/api/category',
  path: '/api/category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddonsRoute = ApiAddonsRouteImport.update({
  id: '/api/addons',
  path: '/api/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersPIndexRoute = UsersPIndexRouteImport.update({
  id: '/users/p/',
  path: '/users/p/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStaffIndexRoute = ReportsStaffIndexRouteImport.update({
  id: '/reports/staff/',
  path: '/reports/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryIndexRoute = ReportsInventoryIndexRouteImport.update({
  id: '/reports/inventory/',
  path: '/reports/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStaffStaffIdRoute = ReportsStaffStaffIdRouteImport.update({
  id: '/reports/staff/$staffId',
  path: '/reports/staff/$staffId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryInventoryIdRoute =
  ReportsInventoryInventoryIdRouteImport.update({
    id: '/reports/inventory/$inventoryId',
    path: '/reports/inventory/$inventoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersSearchRoute = ApiUsersSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiSubscriptionPlansRoute = ApiSubscriptionPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ApiSubscriptionRoute,
} as any)
const ApiStaffReportsStaffIdRoute = ApiStaffReportsStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => ApiStaffReportsRoute,
} as any)
const ApiOrdersOrderHistoryRoute = ApiOrdersOrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => ApiOrdersRoute,
} as any)
const ApiOrdersByTableRoute = ApiOrdersByTableRouteImport.update({
  id: '/by-table',
  path: '/by-table',
  getParentRoute: () => ApiOrdersRoute,
} as any)
const ApiOrdersActionsRoute = ApiOrdersActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => ApiOrdersRoute,
} as any)
const ApiInventoryBulkRoute = ApiInventoryBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ApiInventoryRoute,
} as any)
const ApiCrmStatsRoute = ApiCrmStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiCrmRoute,
} as any)
const ApiCrmDetailsRoute = ApiCrmDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => ApiCrmRoute,
} as any)
const ApiCategoryFromTemplatesRoute =
  ApiCategoryFromTemplatesRouteImport.update({
    id: '/from-templates',
    path: '/from-templates',
    getParentRoute: () => ApiCategoryRoute,
  } as any)
const ApiCategoryCuisineTypesRoute = ApiCategoryCuisineTypesRouteImport.update({
  id: '/cuisine-types',
  path: '/cuisine-types',
  getParentRoute: () => ApiCategoryRoute,
} as any)
const ApiCategoryAsTemplateRoute = ApiCategoryAsTemplateRouteImport.update({
  id: '/as-template',
  path: '/as-template',
  getParentRoute: () => ApiCategoryRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCreateAdminRoute = ApiAuthCreateAdminRouteImport.update({
  id: '/api/auth/create-admin',
  path: '/api/auth/create-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateRoute = ApiAdminUpdateRouteImport.update({
  id: '/api/admin/update',
  path: '/api/admin/update',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoryTemplatesCuisineRoute =
  ApiCategoryTemplatesCuisineRouteImport.update({
    id: '/templates/$cuisine',
    path: '/templates/$cuisine',
    getParentRoute: () => ApiCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/addons': typeof ApiAddonsRoute
  '/api/category': typeof ApiCategoryRouteWithChildren
  '/api/crm': typeof ApiCrmRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/imagekit': typeof ApiImagekitRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/inventory-stats': typeof ApiInventoryStatsRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/quick-bill': typeof ApiQuickBillRoute
  '/api/restaurant': typeof ApiRestaurantRoute
  '/api/staff-reports': typeof ApiStaffReportsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRouteWithChildren
  '/api/table': typeof ApiTableRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/waiter-orders': typeof ApiWaiterOrdersRoute
  '/api/ws-token': typeof ApiWsTokenRoute
  '/billing/book-table': typeof BillingBookTableRoute
  '/billing/quick-bill': typeof BillingQuickBillRoute
  '/inventory/menu': typeof InventoryMenuRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/orders/history': typeof OrdersHistoryRoute
  '/orders/overview': typeof OrdersOverviewRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/billing': typeof BillingIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/auth/create-admin': typeof ApiAuthCreateAdminRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/category/as-template': typeof ApiCategoryAsTemplateRoute
  '/api/category/cuisine-types': typeof ApiCategoryCuisineTypesRoute
  '/api/category/from-templates': typeof ApiCategoryFromTemplatesRoute
  '/api/crm/details': typeof ApiCrmDetailsRoute
  '/api/crm/stats': typeof ApiCrmStatsRoute
  '/api/inventory/bulk': typeof ApiInventoryBulkRoute
  '/api/orders/actions': typeof ApiOrdersActionsRoute
  '/api/orders/by-table': typeof ApiOrdersByTableRoute
  '/api/orders/order-history': typeof ApiOrdersOrderHistoryRoute
  '/api/staff-reports/$staffId': typeof ApiStaffReportsStaffIdRoute
  '/api/subscription/plans': typeof ApiSubscriptionPlansRoute
  '/api/users/search': typeof ApiUsersSearchRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/reports/inventory/$inventoryId': typeof ReportsInventoryInventoryIdRoute
  '/reports/staff/$staffId': typeof ReportsStaffStaffIdRoute
  '/reports/inventory': typeof ReportsInventoryIndexRoute
  '/reports/staff': typeof ReportsStaffIndexRoute
  '/users/p': typeof UsersPIndexRoute
  '/api/category/templates/$cuisine': typeof ApiCategoryTemplatesCuisineRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/addons': typeof ApiAddonsRoute
  '/api/category': typeof ApiCategoryRouteWithChildren
  '/api/crm': typeof ApiCrmRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/imagekit': typeof ApiImagekitRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/inventory-stats': typeof ApiInventoryStatsRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/quick-bill': typeof ApiQuickBillRoute
  '/api/restaurant': typeof ApiRestaurantRoute
  '/api/staff-reports': typeof ApiStaffReportsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRouteWithChildren
  '/api/table': typeof ApiTableRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/waiter-orders': typeof ApiWaiterOrdersRoute
  '/api/ws-token': typeof ApiWsTokenRoute
  '/billing/book-table': typeof BillingBookTableRoute
  '/billing/quick-bill': typeof BillingQuickBillRoute
  '/inventory/menu': typeof InventoryMenuRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/orders/history': typeof OrdersHistoryRoute
  '/orders/overview': typeof OrdersOverviewRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/billing': typeof BillingIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/auth/create-admin': typeof ApiAuthCreateAdminRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/category/as-template': typeof ApiCategoryAsTemplateRoute
  '/api/category/cuisine-types': typeof ApiCategoryCuisineTypesRoute
  '/api/category/from-templates': typeof ApiCategoryFromTemplatesRoute
  '/api/crm/details': typeof ApiCrmDetailsRoute
  '/api/crm/stats': typeof ApiCrmStatsRoute
  '/api/inventory/bulk': typeof ApiInventoryBulkRoute
  '/api/orders/actions': typeof ApiOrdersActionsRoute
  '/api/orders/by-table': typeof ApiOrdersByTableRoute
  '/api/orders/order-history': typeof ApiOrdersOrderHistoryRoute
  '/api/staff-reports/$staffId': typeof ApiStaffReportsStaffIdRoute
  '/api/subscription/plans': typeof ApiSubscriptionPlansRoute
  '/api/users/search': typeof ApiUsersSearchRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/reports/inventory/$inventoryId': typeof ReportsInventoryInventoryIdRoute
  '/reports/staff/$staffId': typeof ReportsStaffStaffIdRoute
  '/reports/inventory': typeof ReportsInventoryIndexRoute
  '/reports/staff': typeof ReportsStaffIndexRoute
  '/users/p': typeof UsersPIndexRoute
  '/api/category/templates/$cuisine': typeof ApiCategoryTemplatesCuisineRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/addons': typeof ApiAddonsRoute
  '/api/category': typeof ApiCategoryRouteWithChildren
  '/api/crm': typeof ApiCrmRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/imagekit': typeof ApiImagekitRoute
  '/api/inventory': typeof ApiInventoryRouteWithChildren
  '/api/inventory-stats': typeof ApiInventoryStatsRoute
  '/api/orders': typeof ApiOrdersRouteWithChildren
  '/api/quick-bill': typeof ApiQuickBillRoute
  '/api/restaurant': typeof ApiRestaurantRoute
  '/api/staff-reports': typeof ApiStaffReportsRouteWithChildren
  '/api/subscription': typeof ApiSubscriptionRouteWithChildren
  '/api/table': typeof ApiTableRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/waiter-orders': typeof ApiWaiterOrdersRoute
  '/api/ws-token': typeof ApiWsTokenRoute
  '/billing/book-table': typeof BillingBookTableRoute
  '/billing/quick-bill': typeof BillingQuickBillRoute
  '/inventory/menu': typeof InventoryMenuRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/orders/history': typeof OrdersHistoryRoute
  '/orders/overview': typeof OrdersOverviewRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/billing/': typeof BillingIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/admin/update': typeof ApiAdminUpdateRoute
  '/api/auth/create-admin': typeof ApiAuthCreateAdminRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/category/as-template': typeof ApiCategoryAsTemplateRoute
  '/api/category/cuisine-types': typeof ApiCategoryCuisineTypesRoute
  '/api/category/from-templates': typeof ApiCategoryFromTemplatesRoute
  '/api/crm/details': typeof ApiCrmDetailsRoute
  '/api/crm/stats': typeof ApiCrmStatsRoute
  '/api/inventory/bulk': typeof ApiInventoryBulkRoute
  '/api/orders/actions': typeof ApiOrdersActionsRoute
  '/api/orders/by-table': typeof ApiOrdersByTableRoute
  '/api/orders/order-history': typeof ApiOrdersOrderHistoryRoute
  '/api/staff-reports/$staffId': typeof ApiStaffReportsStaffIdRoute
  '/api/subscription/plans': typeof ApiSubscriptionPlansRoute
  '/api/users/search': typeof ApiUsersSearchRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/reports/inventory/$inventoryId': typeof ReportsInventoryInventoryIdRoute
  '/reports/staff/$staffId': typeof ReportsStaffStaffIdRoute
  '/reports/inventory/': typeof ReportsInventoryIndexRoute
  '/reports/staff/': typeof ReportsStaffIndexRoute
  '/users/p/': typeof UsersPIndexRoute
  '/api/category/templates/$cuisine': typeof ApiCategoryTemplatesCuisineRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/dashboard'
    | '/login'
    | '/api/addons'
    | '/api/category'
    | '/api/crm'
    | '/api/dashboard'
    | '/api/imagekit'
    | '/api/inventory'
    | '/api/inventory-stats'
    | '/api/orders'
    | '/api/quick-bill'
    | '/api/restaurant'
    | '/api/staff-reports'
    | '/api/subscription'
    | '/api/table'
    | '/api/users'
    | '/api/waiter-orders'
    | '/api/ws-token'
    | '/billing/book-table'
    | '/billing/quick-bill'
    | '/inventory/menu'
    | '/inventory/stock'
    | '/orders/history'
    | '/orders/overview'
    | '/reports/crm'
    | '/reports/sales'
    | '/settings/subscription'
    | '/billing'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/users'
    | '/api/admin/update'
    | '/api/auth/create-admin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/session'
    | '/api/category/as-template'
    | '/api/category/cuisine-types'
    | '/api/category/from-templates'
    | '/api/crm/details'
    | '/api/crm/stats'
    | '/api/inventory/bulk'
    | '/api/orders/actions'
    | '/api/orders/by-table'
    | '/api/orders/order-history'
    | '/api/staff-reports/$staffId'
    | '/api/subscription/plans'
    | '/api/users/search'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/reports/inventory/$inventoryId'
    | '/reports/staff/$staffId'
    | '/reports/inventory'
    | '/reports/staff'
    | '/users/p'
    | '/api/category/templates/$cuisine'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/dashboard'
    | '/login'
    | '/api/addons'
    | '/api/category'
    | '/api/crm'
    | '/api/dashboard'
    | '/api/imagekit'
    | '/api/inventory'
    | '/api/inventory-stats'
    | '/api/orders'
    | '/api/quick-bill'
    | '/api/restaurant'
    | '/api/staff-reports'
    | '/api/subscription'
    | '/api/table'
    | '/api/users'
    | '/api/waiter-orders'
    | '/api/ws-token'
    | '/billing/book-table'
    | '/billing/quick-bill'
    | '/inventory/menu'
    | '/inventory/stock'
    | '/orders/history'
    | '/orders/overview'
    | '/reports/crm'
    | '/reports/sales'
    | '/settings/subscription'
    | '/billing'
    | '/inventory'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/users'
    | '/api/admin/update'
    | '/api/auth/create-admin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/session'
    | '/api/category/as-template'
    | '/api/category/cuisine-types'
    | '/api/category/from-templates'
    | '/api/crm/details'
    | '/api/crm/stats'
    | '/api/inventory/bulk'
    | '/api/orders/actions'
    | '/api/orders/by-table'
    | '/api/orders/order-history'
    | '/api/staff-reports/$staffId'
    | '/api/subscription/plans'
    | '/api/users/search'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/reports/inventory/$inventoryId'
    | '/reports/staff/$staffId'
    | '/reports/inventory'
    | '/reports/staff'
    | '/users/p'
    | '/api/category/templates/$cuisine'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/dashboard'
    | '/login'
    | '/api/addons'
    | '/api/category'
    | '/api/crm'
    | '/api/dashboard'
    | '/api/imagekit'
    | '/api/inventory'
    | '/api/inventory-stats'
    | '/api/orders'
    | '/api/quick-bill'
    | '/api/restaurant'
    | '/api/staff-reports'
    | '/api/subscription'
    | '/api/table'
    | '/api/users'
    | '/api/waiter-orders'
    | '/api/ws-token'
    | '/billing/book-table'
    | '/billing/quick-bill'
    | '/inventory/menu'
    | '/inventory/stock'
    | '/orders/history'
    | '/orders/overview'
    | '/reports/crm'
    | '/reports/sales'
    | '/settings/subscription'
    | '/billing/'
    | '/inventory/'
    | '/orders/'
    | '/reports/'
    | '/settings/'
    | '/staff/'
    | '/users/'
    | '/api/admin/update'
    | '/api/auth/create-admin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/refresh'
    | '/api/auth/session'
    | '/api/category/as-template'
    | '/api/category/cuisine-types'
    | '/api/category/from-templates'
    | '/api/crm/details'
    | '/api/crm/stats'
    | '/api/inventory/bulk'
    | '/api/orders/actions'
    | '/api/orders/by-table'
    | '/api/orders/order-history'
    | '/api/staff-reports/$staffId'
    | '/api/subscription/plans'
    | '/api/users/search'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/reports/inventory/$inventoryId'
    | '/reports/staff/$staffId'
    | '/reports/inventory/'
    | '/reports/staff/'
    | '/users/p/'
    | '/api/category/templates/$cuisine'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiAddonsRoute: typeof ApiAddonsRoute
  ApiCategoryRoute: typeof ApiCategoryRouteWithChildren
  ApiCrmRoute: typeof ApiCrmRouteWithChildren
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiImagekitRoute: typeof ApiImagekitRoute
  ApiInventoryRoute: typeof ApiInventoryRouteWithChildren
  ApiInventoryStatsRoute: typeof ApiInventoryStatsRoute
  ApiOrdersRoute: typeof ApiOrdersRouteWithChildren
  ApiQuickBillRoute: typeof ApiQuickBillRoute
  ApiRestaurantRoute: typeof ApiRestaurantRoute
  ApiStaffReportsRoute: typeof ApiStaffReportsRouteWithChildren
  ApiSubscriptionRoute: typeof ApiSubscriptionRouteWithChildren
  ApiTableRoute: typeof ApiTableRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiWaiterOrdersRoute: typeof ApiWaiterOrdersRoute
  ApiWsTokenRoute: typeof ApiWsTokenRoute
  BillingBookTableRoute: typeof BillingBookTableRoute
  BillingQuickBillRoute: typeof BillingQuickBillRoute
  InventoryMenuRoute: typeof InventoryMenuRoute
  InventoryStockRoute: typeof InventoryStockRoute
  OrdersHistoryRoute: typeof OrdersHistoryRoute
  OrdersOverviewRoute: typeof OrdersOverviewRoute
  ReportsCrmRoute: typeof ReportsCrmRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  BillingIndexRoute: typeof BillingIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApiAdminUpdateRoute: typeof ApiAdminUpdateRoute
  ApiAuthCreateAdminRoute: typeof ApiAuthCreateAdminRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ReportsInventoryInventoryIdRoute: typeof ReportsInventoryInventoryIdRoute
  ReportsStaffStaffIdRoute: typeof ReportsStaffStaffIdRoute
  ReportsInventoryIndexRoute: typeof ReportsInventoryIndexRoute
  ReportsStaffIndexRoute: typeof ReportsStaffIndexRoute
  UsersPIndexRoute: typeof UsersPIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/crm': {
      id: '/reports/crm'
      path: '/reports/crm'
      fullPath: '/reports/crm'
      preLoaderRoute: typeof ReportsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/overview': {
      id: '/orders/overview'
      path: '/orders/overview'
      fullPath: '/orders/overview'
      preLoaderRoute: typeof OrdersOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/history': {
      id: '/orders/history'
      path: '/orders/history'
      fullPath: '/orders/history'
      preLoaderRoute: typeof OrdersHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/stock': {
      id: '/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof InventoryStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/menu': {
      id: '/inventory/menu'
      path: '/inventory/menu'
      fullPath: '/inventory/menu'
      preLoaderRoute: typeof InventoryMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/quick-bill': {
      id: '/billing/quick-bill'
      path: '/billing/quick-bill'
      fullPath: '/billing/quick-bill'
      preLoaderRoute: typeof BillingQuickBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/book-table': {
      id: '/billing/book-table'
      path: '/billing/book-table'
      fullPath: '/billing/book-table'
      preLoaderRoute: typeof BillingBookTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws-token': {
      id: '/api/ws-token'
      path: '/api/ws-token'
      fullPath: '/api/ws-token'
      preLoaderRoute: typeof ApiWsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waiter-orders': {
      id: '/api/waiter-orders'
      path: '/api/waiter-orders'
      fullPath: '/api/waiter-orders'
      preLoaderRoute: typeof ApiWaiterOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/table': {
      id: '/api/table'
      path: '/api/table'
      fullPath: '/api/table'
      preLoaderRoute: typeof ApiTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff-reports': {
      id: '/api/staff-reports'
      path: '/api/staff-reports'
      fullPath: '/api/staff-reports'
      preLoaderRoute: typeof ApiStaffReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/restaurant': {
      id: '/api/restaurant'
      path: '/api/restaurant'
      fullPath: '/api/restaurant'
      preLoaderRoute: typeof ApiRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quick-bill': {
      id: '/api/quick-bill'
      path: '/api/quick-bill'
      fullPath: '/api/quick-bill'
      preLoaderRoute: typeof ApiQuickBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory-stats': {
      id: '/api/inventory-stats'
      path: '/api/inventory-stats'
      fullPath: '/api/inventory-stats'
      preLoaderRoute: typeof ApiInventoryStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory': {
      id: '/api/inventory'
      path: '/api/inventory'
      fullPath: '/api/inventory'
      preLoaderRoute: typeof ApiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imagekit': {
      id: '/api/imagekit'
      path: '/api/imagekit'
      fullPath: '/api/imagekit'
      preLoaderRoute: typeof ApiImagekitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm': {
      id: '/api/crm'
      path: '/api/crm'
      fullPath: '/api/crm'
      preLoaderRoute: typeof ApiCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category': {
      id: '/api/category'
      path: '/api/category'
      fullPath: '/api/category'
      preLoaderRoute: typeof ApiCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/addons': {
      id: '/api/addons'
      path: '/api/addons'
      fullPath: '/api/addons'
      preLoaderRoute: typeof ApiAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/p/': {
      id: '/users/p/'
      path: '/users/p'
      fullPath: '/users/p'
      preLoaderRoute: typeof UsersPIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/staff/': {
      id: '/reports/staff/'
      path: '/reports/staff'
      fullPath: '/reports/staff'
      preLoaderRoute: typeof ReportsStaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory/': {
      id: '/reports/inventory/'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/staff/$staffId': {
      id: '/reports/staff/$staffId'
      path: '/reports/staff/$staffId'
      fullPath: '/reports/staff/$staffId'
      preLoaderRoute: typeof ReportsStaffStaffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory/$inventoryId': {
      id: '/reports/inventory/$inventoryId'
      path: '/reports/inventory/$inventoryId'
      fullPath: '/reports/inventory/$inventoryId'
      preLoaderRoute: typeof ReportsInventoryInventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/search': {
      id: '/api/users/search'
      path: '/search'
      fullPath: '/api/users/search'
      preLoaderRoute: typeof ApiUsersSearchRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/subscription/plans': {
      id: '/api/subscription/plans'
      path: '/plans'
      fullPath: '/api/subscription/plans'
      preLoaderRoute: typeof ApiSubscriptionPlansRouteImport
      parentRoute: typeof ApiSubscriptionRoute
    }
    '/api/staff-reports/$staffId': {
      id: '/api/staff-reports/$staffId'
      path: '/$staffId'
      fullPath: '/api/staff-reports/$staffId'
      preLoaderRoute: typeof ApiStaffReportsStaffIdRouteImport
      parentRoute: typeof ApiStaffReportsRoute
    }
    '/api/orders/order-history': {
      id: '/api/orders/order-history'
      path: '/order-history'
      fullPath: '/api/orders/order-history'
      preLoaderRoute: typeof ApiOrdersOrderHistoryRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
    '/api/orders/by-table': {
      id: '/api/orders/by-table'
      path: '/by-table'
      fullPath: '/api/orders/by-table'
      preLoaderRoute: typeof ApiOrdersByTableRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
    '/api/orders/actions': {
      id: '/api/orders/actions'
      path: '/actions'
      fullPath: '/api/orders/actions'
      preLoaderRoute: typeof ApiOrdersActionsRouteImport
      parentRoute: typeof ApiOrdersRoute
    }
    '/api/inventory/bulk': {
      id: '/api/inventory/bulk'
      path: '/bulk'
      fullPath: '/api/inventory/bulk'
      preLoaderRoute: typeof ApiInventoryBulkRouteImport
      parentRoute: typeof ApiInventoryRoute
    }
    '/api/crm/stats': {
      id: '/api/crm/stats'
      path: '/stats'
      fullPath: '/api/crm/stats'
      preLoaderRoute: typeof ApiCrmStatsRouteImport
      parentRoute: typeof ApiCrmRoute
    }
    '/api/crm/details': {
      id: '/api/crm/details'
      path: '/details'
      fullPath: '/api/crm/details'
      preLoaderRoute: typeof ApiCrmDetailsRouteImport
      parentRoute: typeof ApiCrmRoute
    }
    '/api/category/from-templates': {
      id: '/api/category/from-templates'
      path: '/from-templates'
      fullPath: '/api/category/from-templates'
      preLoaderRoute: typeof ApiCategoryFromTemplatesRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
    '/api/category/cuisine-types': {
      id: '/api/category/cuisine-types'
      path: '/cuisine-types'
      fullPath: '/api/category/cuisine-types'
      preLoaderRoute: typeof ApiCategoryCuisineTypesRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
    '/api/category/as-template': {
      id: '/api/category/as-template'
      path: '/as-template'
      fullPath: '/api/category/as-template'
      preLoaderRoute: typeof ApiCategoryAsTemplateRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/create-admin': {
      id: '/api/auth/create-admin'
      path: '/api/auth/create-admin'
      fullPath: '/api/auth/create-admin'
      preLoaderRoute: typeof ApiAuthCreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update': {
      id: '/api/admin/update'
      path: '/api/admin/update'
      fullPath: '/api/admin/update'
      preLoaderRoute: typeof ApiAdminUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category/templates/$cuisine': {
      id: '/api/category/templates/$cuisine'
      path: '/templates/$cuisine'
      fullPath: '/api/category/templates/$cuisine'
      preLoaderRoute: typeof ApiCategoryTemplatesCuisineRouteImport
      parentRoute: typeof ApiCategoryRoute
    }
  }
}

interface ApiCategoryRouteChildren {
  ApiCategoryAsTemplateRoute: typeof ApiCategoryAsTemplateRoute
  ApiCategoryCuisineTypesRoute: typeof ApiCategoryCuisineTypesRoute
  ApiCategoryFromTemplatesRoute: typeof ApiCategoryFromTemplatesRoute
  ApiCategoryTemplatesCuisineRoute: typeof ApiCategoryTemplatesCuisineRoute
}

const ApiCategoryRouteChildren: ApiCategoryRouteChildren = {
  ApiCategoryAsTemplateRoute: ApiCategoryAsTemplateRoute,
  ApiCategoryCuisineTypesRoute: ApiCategoryCuisineTypesRoute,
  ApiCategoryFromTemplatesRoute: ApiCategoryFromTemplatesRoute,
  ApiCategoryTemplatesCuisineRoute: ApiCategoryTemplatesCuisineRoute,
}

const ApiCategoryRouteWithChildren = ApiCategoryRoute._addFileChildren(
  ApiCategoryRouteChildren,
)

interface ApiCrmRouteChildren {
  ApiCrmDetailsRoute: typeof ApiCrmDetailsRoute
  ApiCrmStatsRoute: typeof ApiCrmStatsRoute
}

const ApiCrmRouteChildren: ApiCrmRouteChildren = {
  ApiCrmDetailsRoute: ApiCrmDetailsRoute,
  ApiCrmStatsRoute: ApiCrmStatsRoute,
}

const ApiCrmRouteWithChildren =
  ApiCrmRoute._addFileChildren(ApiCrmRouteChildren)

interface ApiInventoryRouteChildren {
  ApiInventoryBulkRoute: typeof ApiInventoryBulkRoute
}

const ApiInventoryRouteChildren: ApiInventoryRouteChildren = {
  ApiInventoryBulkRoute: ApiInventoryBulkRoute,
}

const ApiInventoryRouteWithChildren = ApiInventoryRoute._addFileChildren(
  ApiInventoryRouteChildren,
)

interface ApiOrdersRouteChildren {
  ApiOrdersActionsRoute: typeof ApiOrdersActionsRoute
  ApiOrdersByTableRoute: typeof ApiOrdersByTableRoute
  ApiOrdersOrderHistoryRoute: typeof ApiOrdersOrderHistoryRoute
}

const ApiOrdersRouteChildren: ApiOrdersRouteChildren = {
  ApiOrdersActionsRoute: ApiOrdersActionsRoute,
  ApiOrdersByTableRoute: ApiOrdersByTableRoute,
  ApiOrdersOrderHistoryRoute: ApiOrdersOrderHistoryRoute,
}

const ApiOrdersRouteWithChildren = ApiOrdersRoute._addFileChildren(
  ApiOrdersRouteChildren,
)

interface ApiStaffReportsRouteChildren {
  ApiStaffReportsStaffIdRoute: typeof ApiStaffReportsStaffIdRoute
}

const ApiStaffReportsRouteChildren: ApiStaffReportsRouteChildren = {
  ApiStaffReportsStaffIdRoute: ApiStaffReportsStaffIdRoute,
}

const ApiStaffReportsRouteWithChildren = ApiStaffReportsRoute._addFileChildren(
  ApiStaffReportsRouteChildren,
)

interface ApiSubscriptionRouteChildren {
  ApiSubscriptionPlansRoute: typeof ApiSubscriptionPlansRoute
}

const ApiSubscriptionRouteChildren: ApiSubscriptionRouteChildren = {
  ApiSubscriptionPlansRoute: ApiSubscriptionPlansRoute,
}

const ApiSubscriptionRouteWithChildren = ApiSubscriptionRoute._addFileChildren(
  ApiSubscriptionRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersSearchRoute: typeof ApiUsersSearchRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersSearchRoute: ApiUsersSearchRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiAddonsRoute: ApiAddonsRoute,
  ApiCategoryRoute: ApiCategoryRouteWithChildren,
  ApiCrmRoute: ApiCrmRouteWithChildren,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiImagekitRoute: ApiImagekitRoute,
  ApiInventoryRoute: ApiInventoryRouteWithChildren,
  ApiInventoryStatsRoute: ApiInventoryStatsRoute,
  ApiOrdersRoute: ApiOrdersRouteWithChildren,
  ApiQuickBillRoute: ApiQuickBillRoute,
  ApiRestaurantRoute: ApiRestaurantRoute,
  ApiStaffReportsRoute: ApiStaffReportsRouteWithChildren,
  ApiSubscriptionRoute: ApiSubscriptionRouteWithChildren,
  ApiTableRoute: ApiTableRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiWaiterOrdersRoute: ApiWaiterOrdersRoute,
  ApiWsTokenRoute: ApiWsTokenRoute,
  BillingBookTableRoute: BillingBookTableRoute,
  BillingQuickBillRoute: BillingQuickBillRoute,
  InventoryMenuRoute: InventoryMenuRoute,
  InventoryStockRoute: InventoryStockRoute,
  OrdersHistoryRoute: OrdersHistoryRoute,
  OrdersOverviewRoute: OrdersOverviewRoute,
  ReportsCrmRoute: ReportsCrmRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  BillingIndexRoute: BillingIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApiAdminUpdateRoute: ApiAdminUpdateRoute,
  ApiAuthCreateAdminRoute: ApiAuthCreateAdminRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ReportsInventoryInventoryIdRoute: ReportsInventoryInventoryIdRoute,
  ReportsStaffStaffIdRoute: ReportsStaffStaffIdRoute,
  ReportsInventoryIndexRoute: ReportsInventoryIndexRoute,
  ReportsStaffIndexRoute: ReportsStaffIndexRoute,
  UsersPIndexRoute: UsersPIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
