services:
  delycia-server:
    container_name: delycia-server-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    ports:
      - "8020:8020"

    env_file:
      - .env

    environment:
      PORT: 8020
      NODE_ENV: production

      # Redis
      REDIS_HOST: delycia-redis
      REDIS_PORT: 6379
      REDIS_URL: redis://delycia-redis:6379

    depends_on:
      - delycia-redis

    networks:
      - delycia-network

  delycia-redis:
    image: redis:7-alpine
    container_name: delycia-redis-container
    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - delycia_redis_data:/data

    networks:
      - delycia-network

volumes:
  delycia_redis_data:

networks:
  delycia-network:
    driver: bridge