/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as MenusRouteImport } from './routes/menus'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants/index'
import { Route as MenusIndexRouteImport } from './routes/menus/index'
import { Route as UsersIdRouteImport } from './routes/users/$id'
import { Route as SubscriptionsPlansRouteImport } from './routes/subscriptions.plans'
import { Route as SubscriptionsAssignmentsRouteImport } from './routes/subscriptions.assignments'
import { Route as StaffIdRouteImport } from './routes/staff/$id'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants/$id'
import { Route as SubscriptionsPlansIndexRouteImport } from './routes/subscriptions/plans/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const MenusRoute = MenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantsRoute,
} as any)
const MenusIndexRoute = MenusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenusRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRoute,
} as any)
const SubscriptionsPlansRoute = SubscriptionsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const SubscriptionsAssignmentsRoute =
  SubscriptionsAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => SubscriptionsRoute,
  } as any)
const StaffIdRoute = StaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffRoute,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)
const SubscriptionsPlansIndexRoute = SubscriptionsPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriptionsPlansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menus': typeof MenusRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/support': typeof SupportRoute
  '/users': typeof UsersRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/staff/$id': typeof StaffIdRoute
  '/subscriptions/assignments': typeof SubscriptionsAssignmentsRoute
  '/subscriptions/plans': typeof SubscriptionsPlansRouteWithChildren
  '/users/$id': typeof UsersIdRoute
  '/menus/': typeof MenusIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/users/': typeof UsersIndexRoute
  '/subscriptions/plans/': typeof SubscriptionsPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/support': typeof SupportRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/staff/$id': typeof StaffIdRoute
  '/subscriptions/assignments': typeof SubscriptionsAssignmentsRoute
  '/users/$id': typeof UsersIdRoute
  '/menus': typeof MenusIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/users': typeof UsersIndexRoute
  '/subscriptions/plans': typeof SubscriptionsPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/menus': typeof MenusRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/support': typeof SupportRoute
  '/users': typeof UsersRouteWithChildren
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/staff/$id': typeof StaffIdRoute
  '/subscriptions/assignments': typeof SubscriptionsAssignmentsRoute
  '/subscriptions/plans': typeof SubscriptionsPlansRouteWithChildren
  '/users/$id': typeof UsersIdRoute
  '/menus/': typeof MenusIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/users/': typeof UsersIndexRoute
  '/subscriptions/plans/': typeof SubscriptionsPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/menus'
    | '/restaurants'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/support'
    | '/users'
    | '/restaurants/$id'
    | '/staff/$id'
    | '/subscriptions/assignments'
    | '/subscriptions/plans'
    | '/users/$id'
    | '/menus/'
    | '/restaurants/'
    | '/staff/'
    | '/users/'
    | '/subscriptions/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/restaurants/$id'
    | '/staff/$id'
    | '/subscriptions/assignments'
    | '/users/$id'
    | '/menus'
    | '/restaurants'
    | '/staff'
    | '/users'
    | '/subscriptions/plans'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/menus'
    | '/restaurants'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/support'
    | '/users'
    | '/restaurants/$id'
    | '/staff/$id'
    | '/subscriptions/assignments'
    | '/subscriptions/plans'
    | '/users/$id'
    | '/menus/'
    | '/restaurants/'
    | '/staff/'
    | '/users/'
    | '/subscriptions/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MenusRoute: typeof MenusRouteWithChildren
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
  SupportRoute: typeof SupportRoute
  UsersRoute: typeof UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menus': {
      id: '/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/menus/': {
      id: '/menus/'
      path: '/'
      fullPath: '/menus/'
      preLoaderRoute: typeof MenusIndexRouteImport
      parentRoute: typeof MenusRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/subscriptions/plans': {
      id: '/subscriptions/plans'
      path: '/plans'
      fullPath: '/subscriptions/plans'
      preLoaderRoute: typeof SubscriptionsPlansRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/subscriptions/assignments': {
      id: '/subscriptions/assignments'
      path: '/assignments'
      fullPath: '/subscriptions/assignments'
      preLoaderRoute: typeof SubscriptionsAssignmentsRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/staff/$id': {
      id: '/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof StaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/subscriptions/plans/': {
      id: '/subscriptions/plans/'
      path: '/'
      fullPath: '/subscriptions/plans/'
      preLoaderRoute: typeof SubscriptionsPlansIndexRouteImport
      parentRoute: typeof SubscriptionsPlansRoute
    }
  }
}

interface MenusRouteChildren {
  MenusIndexRoute: typeof MenusIndexRoute
}

const MenusRouteChildren: MenusRouteChildren = {
  MenusIndexRoute: MenusIndexRoute,
}

const MenusRouteWithChildren = MenusRoute._addFileChildren(MenusRouteChildren)

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

interface StaffRouteChildren {
  StaffIdRoute: typeof StaffIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIdRoute: StaffIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface SubscriptionsPlansRouteChildren {
  SubscriptionsPlansIndexRoute: typeof SubscriptionsPlansIndexRoute
}

const SubscriptionsPlansRouteChildren: SubscriptionsPlansRouteChildren = {
  SubscriptionsPlansIndexRoute: SubscriptionsPlansIndexRoute,
}

const SubscriptionsPlansRouteWithChildren =
  SubscriptionsPlansRoute._addFileChildren(SubscriptionsPlansRouteChildren)

interface SubscriptionsRouteChildren {
  SubscriptionsAssignmentsRoute: typeof SubscriptionsAssignmentsRoute
  SubscriptionsPlansRoute: typeof SubscriptionsPlansRouteWithChildren
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsAssignmentsRoute: SubscriptionsAssignmentsRoute,
  SubscriptionsPlansRoute: SubscriptionsPlansRouteWithChildren,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

interface UsersRouteChildren {
  UsersIdRoute: typeof UsersIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIdRoute: UsersIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MenusRoute: MenusRouteWithChildren,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
  SupportRoute: SupportRoute,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
